"""Pydantic request and response schemas for AskRhys AI Copilot."""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional
import uuid
from pydantic import BaseModel, Field


class ContextMode(str, Enum):
    """Context modes supported by AskRhys."""
    GENERAL = "general"
    PROJECT = "project"
    SELECTION = "selection"


class ChatMessage(BaseModel):
    """Single conversational turn in AskRhys dialog history."""
    role: Literal["user", "assistant", "system"] = Field(
        ...,
        description="Role of the turn: user, assistant, or system.",
    )
    content: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Text content of the message.",
    )


class ProjectEditSuggestion(BaseModel):
    """Structured, non-mutating project change recommendation."""
    type: Literal["project_edit_suggestion"] = Field(
        default="project_edit_suggestion",
        description="Discriminator tag for client-side suggestion handling.",
    )
    operation: str = Field(
        ...,
        description="Suggested operation name (e.g., 'update_scene_script', 'adjust_duration', 'suggest_visual').",
    )
    scene_id: Optional[str] = Field(
        default=None,
        description="Scene identifier if suggestion targets a specific scene.",
    )
    reason: str = Field(
        ...,
        description="Explanation of why this edit improves the video.",
    )
    proposed_value: Any = Field(
        ...,
        description="Proposed replacement value or structured parameters.",
    )


class AskRhysRequest(BaseModel):
    """Request payload sent to AskRhys conversational endpoint."""
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="User's prompt or question for AskRhys.",
    )
    project_id: Optional[uuid.UUID] = Field(
        default=None,
        description="Optional active project ID for project-aware context.",
    )
    conversation_id: Optional[str] = Field(
        default=None,
        description="Optional client conversation tracking identifier.",
    )
    context_mode: ContextMode = Field(
        default=ContextMode.GENERAL,
        description="Context mode: 'general', 'project', or 'selection'.",
    )
    history: Optional[List[ChatMessage]] = Field(
        default_factory=list,
        description="Bounded conversational history from client (up to 6 previous messages).",
    )


class AskRhysResponse(BaseModel):
    """Structured response returned by AskRhys conversational endpoint."""
    conversation_id: str = Field(
        ...,
        description="Conversation session identifier.",
    )
    message: str = Field(
        ...,
        description="Echo of user's query prompt.",
    )
    response: str = Field(
        ...,
        description="Truthful response generated by local Qwen 2.5 0.5B ONNX CPU model.",
    )
    context_used: bool = Field(
        default=False,
        description="Whether active project context was incorporated into inference.",
    )
    provider: str = Field(
        default="qwen",
        description="AI provider name that generated the response.",
    )
    model: str = Field(
        default="llm/qwen-2.5-0.5b-cpu",
        description="Specific model identifier used.",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="End-to-end inference and orchestration latency in milliseconds.",
    )
    suggestions: List[str] = Field(
        default_factory=list,
        description="Follow-up quick reply suggestions or prompt tips.",
    )
    actions: List[ProjectEditSuggestion] = Field(
        default_factory=list,
        description="Non-mutating project edit recommendations proposed for explicit user review.",
    )
